name: My first workflow
on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a
      - name: Print working directory
        run: pwd
      - name: create js file
        run: echo 'console.log("he,lo World!");' > app.js
      - name: List all files
        run: ls -a

  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: CPU architecture
        run: lscpu
      - name: Sytem Architecture
        run: uname -m
      - name: Ram
        run: free -h
      - name: SSD Info
        run: df -h
      - name: Hardware details about your storage drive
        run: sudo lshw -class disk
      - name: Run Multiline Script
        run: |
          echo "Starting Script"
          uname -r
          nproc
          lsblk
